### ISSUE TITLE
V8 will not garbage collection?

### ISSUE THREAD

**Issue by pigLoveRabbit520** [rogchap/v8go#197] opened 2021-10-18 03:56 UTC
I will load a helper script in advance:
```
ctx, _ = v8go.NewContext(iso)
_, err = ctx.RunScript(content, "tool.js")
```
`tool.js` just contains a helper class like this:
```
class Helper {
  add(a, b) { return a +b; }
}
```
And I will invoke `Helper.add` function many times:
```
a, b := 4, 5
val, err := ctx.RunScript("(function(){ const h = new  Helper();  return h.add(%d, %d)) })();", "")
```
I found `UsedHeapSize` of **iso** continuously increased and never went down, V8 will not gc?

**Comment by dylanahsmith** [comment] 2021-10-18 14:07
Duplicate of https://github.com/rogchap/v8go/issues/105

**Closed by dylanahsmith** 2021-10-18 14:07 UTC
