### ISSUE TITLE
implement an import function

### ISSUE THREAD

**Issue by Meraj** [rogchap/v8go#237] opened 2021-11-20 15:13 UTC
hi,
i want to write an import function to use it in the JS file,
for example in JS file when client use:
```
import("printFunc")
printFunc("hello")
```
the printFunc.js will be loaded for the current context
i do implement something like that but it is not working
i do added a javascript function with golang callback with name imports, and when user call this function in JS file golang callback will be load another JS file for current context, but i can not access to the loaded js file functions in the current running js file

**Comment by pigLoveRabbit520** [comment] 2021-11-21 07:44
you can use [esbuild](https://esbuild.github.io/) to get a bundle file.

**Comment by tv42** [comment] 2021-12-17 20:47
This is somewhat a duplicate of https://github.com/rogchap/v8go/issues/99. They ask for different things, but the likely fix is the same for both.

**Comment by dylanahsmith** [comment] 2021-12-21 20:20
That syntax is for ES modules, which V8 has support for, but v8go doesn't yet expose.  This is indeed a duplicate of #99.

**Closed by dylanahsmith** 2021-12-21 20:20 UTC
